version: '3.9'

services:
  db:
    image: postgres:13
    container_name: django_sessionsbank_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgresdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234

  web:
    build: .
    container_name: django_sessionsbank_backend_web
    command: 
      python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
