# Generated by Django 4.2.5 on 2024-05-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('balance', models.FloatField(blank=True, null=True, verbose_name='balane')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
